# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flixr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flixr
pod "AlamofireImage"

  target 'FlixrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixrUITests' do
    # Pods for testing
  end

end
